# Form implementation generated from reading ui file 'part1good.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 361, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.characterLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.characterLabel.setObjectName("characterLabel")
        self.verticalLayout.addWidget(self.characterLabel)
        self.characterSlider = QtWidgets.QSlider(parent=self.layoutWidget)
        self.characterSlider.setMinimum(6)
        self.characterSlider.setMaximum(24)
        self.characterSlider.setPageStep(1)
        self.characterSlider.setSliderPosition(10)
        self.characterSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.characterSlider.setObjectName("characterSlider")
        self.verticalLayout.addWidget(self.characterSlider)
        self.generateButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.generateButton.setObjectName("generateButton")
        self.verticalLayout.addWidget(self.generateButton)
        self.resultLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.resultLabel.setObjectName("resultLabel")
        self.verticalLayout.addWidget(self.resultLabel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Password Generator"))
        self.characterLabel.setText(_translate("MainWindow", "# of Characters: 10"))
        self.generateButton.setText(_translate("MainWindow", "Generate a password"))
        self.resultLabel.setText(_translate("MainWindow", "Your New Password:"))
